use_frameworks!

platform :ios, '9.0'

target 'NBLImageCropper_Example' do
  pod 'NBLImageCropper', :path => '../'

  target 'NBLImageCropper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
